trigger:
    - main

jobs:
    -
        job: Run_Test_Config

        strategy:
            maxParallel: 1
            matrix:
                linux:
                    imageName: 'ubuntu-latest'
                mac:
                    imageName: 'macOS-latest'
                windows:
                    imageName: 'windows-latest'
      
        pool: 
            vmImage: $(imageName)
        steps:
            -
                template: templates/run-test-config.yml
                parameters:
                    clientID: client:dai:agent:integration
                    serverURL: https://foomunle-aub-12401-6.dai.webperfdev.com
                    testConfigID: 3d41a425-cd7a-4c93-9741-5dd1c007222c
                    clientSecret: e9c15662-8c1b-472e-930d-aa0b11726093
                    gitlabAccessToken: glpat-yCM3Y2u-NobKzxZL_oro
                    dryRun: false
